[build]
	command = "npm run build"
	base = "."
	publish = ".next"

[build.environment]
	NEXT_USE_NETLIFY_EDGE = "true"
	NEXT_FORCE_EDGE_IMAGES = "true"

[[plugins]]
	package = "@netlify/plugin-nextjs"

[[plugins]]
	package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://mahd.comboompunksucht.app"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "./.next/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

[[plugins]]
	package = "netlify-plugin-chromium"
    [plugins.inputs]
		packageManager = "npm"
		setChromePathInEnv = false
		failBuildOnError = false

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
	package = "@netlify/plugin-lighthouse"

	# optional, deploy the lighthouse report to a path under your site
	[plugins.inputs.audits]
    	output_path = "./.next/lighthouse.html"

	[plugins.inputs.settings]
    	preset = "desktop"
		locale = "de"

[[redirects]]
	from = "/_next/static/*"
	to = "/static/:splat"
	status = 200

[functions]
	included_files = [
		"!node_modules/sharp/vendor/8.12.2/darwin-*/**/*",
		"!node_modules/sharp/build/Release/sharp-darwin-*"
	]