name: Tauri Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Adjust this to match your Node.js version

    - name: Install dependencies
      run: yarn install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: cargo

    - name: Build Tauri app
      run: yarn tauri build --release
      env:
        CI: true

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: tauri-build-${{ matrix.os }}
        path: |
          src-tauri/target/release/bundle/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: gh-action-create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src-tauri/target/release/bundle/*
        asset_name: tauri_build_${{ github.ref }}
        asset_content_type: application/zip