name: Tauri Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: cargo

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libsoup-3.0-dev libwebkit2gtk-4.0-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install gtk+3 libsoup

    - name: Set PKG_CONFIG_PATH
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

    - name: Build Tauri app
      run: yarn tauri build
      env:
        CI: true

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: tauri-build-${{ matrix.os }}
        path: src-tauri/target/release/bundle/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: src-tauri/target/release/bundle/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}