name: Build and Release Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tauri-build
        uses: JonasKruckenberg/tauri-build@tauri-build-v1.5.11
