name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # Läuft alle 5 Minuten
  workflow_dispatch:

jobs:
  # Sync for dev branch
  sync_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Git-Credentials bleiben erhalten
          fetch-depth: 0 # Hol alle Branches und Tags

      - name: Set up Git
        run: |
          git config user.name 'mcpeaps_HD'
          git config user.email 'mcpeaps_HD@outlook.com'

      - name: Add upstream repository
        run: |
          git remote add upstream 'https://github.com/comboomPunkTsucht/comboom.sucht-BLOG.git'
          git fetch upstream

      - name: Sync dev branch
        run: |
          git fetch upstream dev # Fetch the latest upstream dev branch
          git checkout -B dev upstream/dev # Check out upstream dev explicitly
          git rebase upstream/dev || git rebase --abort
          git merge -X theirs upstream/dev
          git push origin dev --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Sync for main branch, depends on dev sync success
  sync_main:
    runs-on: ubuntu-latest
    needs: sync_dev # This makes main sync depend on dev sync success

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Git-Credentials bleiben erhalten
          fetch-depth: 0 # Hol alle Branches und Tags

      - name: Set up Git
        run: |
          git config user.name 'mcpeaps_HD'
          git config user.email 'mcpeaps_HD@outlook.com'

      - name: Add upstream repository
        run: |
          git remote add upstream 'https://github.com/comboomPunkTsucht/comboom.sucht-BLOG.git'
          git fetch upstream

      - name: Sync main branch
        run: |
          git fetch upstream main # Fetch the latest upstream main branch
          git checkout -B main upstream/main # Check out upstream main explicitly
          git rebase upstream/main || git rebase --abort
          git merge -X theirs upstream/main
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}